"""add role in workspacemember

Revision ID: 19bf552ddb47
Revises: 4b6fdd70e32c
Create Date: 2026-09-05 16:03:05.767769

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '19bf552ddb47'
down_revision: Union[str, Sequence[str], None] = '4b6fdd70e32c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workspace_members', sa.Column('role', sa.String(length=20), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('workspace_members', 'role')
    # ### end Alembic commands ###
