"""add dm message attachments

Revision ID: 277835b0335c
Revises: e7899461c112
Create Date: 2026-09-15 19:28:42.541737

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '277835b0335c'
down_revision: Union[str, Sequence[str], None] = 'e7899461c112'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('message_attachments', sa.Column('dm_message_id', sa.Integer(), nullable=True))
    op.alter_column('message_attachments', 'message_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.create_foreign_key(
    'fk_message_attachments_dm_message_id',
    'message_attachments',
    'dm_messages',
    ['dm_message_id'],
    ['id'],
    ondelete='CASCADE'
)
    op.create_check_constraint('ck_attachment_one_message', 'message_attachments', '(message_id IS NOT NULL AND dm_message_id IS NULL) OR (message_id IS NULL AND dm_message_id IS NOT NULL)')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('ck_attachment_one_message', 'message_attachments', type_='check')
    op.drop_constraint(
    'fk_message_attachments_dm_message_id',
    'message_attachments',
    type_='foreignkey'
)
    op.alter_column('message_attachments', 'message_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.drop_column('message_attachments', 'dm_message_id')
    # ### end Alembic commands ###
