"""add user profile fields

Revision ID: 36236368eb3e
Revises: cda172f62b14
Create Date: 2026-08-16 14:49:55.881139

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '36236368eb3e'
down_revision: Union[str, Sequence[str], None] = 'cda172f62b14'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""

    op.add_column(
        'users',
        sa.Column('handle', sa.String(length=100), nullable=True)
    )

    op.add_column(
        'users',
        sa.Column('avatar_url', sa.String(length=500), nullable=True)
    )

    op.add_column(
        'users',
        sa.Column('bio', sa.String(length=500), nullable=True)
    )

    op.add_column(
        'users',
        sa.Column(
            'status',
            sa.String(length=50),
            nullable=False,
            server_default='offline'
        )
    )

    op.add_column(
        'users',
        sa.Column('custom_status', sa.String(length=255), nullable=True)
    )

    # Backfill existing users
    op.execute(
        "UPDATE users SET handle = username"
    )

    # Now that existing rows have values,
    # enforce the constraints.
    op.alter_column(
        'users',
        'handle',
        existing_type=sa.String(length=100),
        nullable=False
    )

    op.create_unique_constraint(
        'uq_users_handle',
        'users',
        ['handle']
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_column('users', 'custom_status')
    op.drop_column('users', 'status')
    op.drop_column('users', 'bio')
    op.drop_column('users', 'avatar_url')
    op.drop_column('users', 'handle')
    # ### end Alembic commands ###
