""" modify reset password

Revision ID: 77056abc9b83
Revises: 145a2f4c0971
Create Date: 2026-08-23 15:43:07.249390

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '77056abc9b83'
down_revision: Union[str, Sequence[str], None] = '145a2f4c0971'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('password_resets', sa.Column('reset_token_hash', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('password_resets', 'reset_token_hash')
    # ### end Alembic commands ###
