"""add name for db conversation

Revision ID: 950a9716cf10
Revises: e9dcd417e21d
Create Date: 2026-10-01 18:53:16.871952

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '950a9716cf10'
down_revision: Union[str, Sequence[str], None] = 'e9dcd417e21d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dm_conversations', sa.Column('name', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    op.drop_column('dm_conversations', 'name')
    # ### end Alembic commands ###
